#!/bin/bash
main
HEAD
update_script
master
HEAD
echo "ALX School is so cool!"
echo "ALX School"
update_script
main
echo "ALX School is so cool!"
echo "ALX School"
master
0cd47088c0b204568cbfdf32106b89ad4f1116f6
update_script
main
master
HEAD
HEAD
echo "ALX School is so cool!"
echo "ALX School"
update_script
main
echo "ALX School is so cool!"
echo "ALX School"
update_script
master
0cd47088c0b204568cbfdf32106b89ad4f1116f6
master
master
0cd47088c0b204568cbfdf32106b89ad4f1116f6
master
master